name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: mytest
      id: mytest
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: mytest
        setup-command: ''
        command: python test.py
        input: ''
        expected-output: Hello
        comparison-method: exact
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MYTEST_RESULTS: "${{steps.mytest.outputs.result}}"
      with:
        runners: mytest
